In [1]:
import numpy as np


In [2]:
simple_list = [9, 18, 27]
np.array(simple_list)

array([ 9, 18, 27])

In [3]:
arr = np.array([9, 18, 27])
arr


array([ 9, 18, 27])

In [4]:
list_of_lists = ([9, 18, 27], [5, 10, 25], [7, 14, 47])
np.array(list_of_lists)


array([[ 9, 18, 27],
       [ 5, 10, 25],
       [ 7, 14, 47]])

In [5]:
arr = np.array([[4,5,9],[8,24,16],[2,4,9]])
arr


array([[ 4,  5,  9],
       [ 8, 24, 16],
       [ 2,  4,  9]])

In [6]:
np.arange(4, 64) # Will arrange numbers from 4 to 64 discluding 64

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63])

In [7]:
np.arange(4, 64, 4) # Will arrange numbers from 4 to 64 discluding 64 with a step of 4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [8]:
np.zeros(9) # Will give an array of 9 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

In [10]:
np.ones(4) #Will give an array of four ones

array([1., 1., 1., 1.])

In [11]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [12]:
np.ones((3, 9), dtype = int) # This method workd with only ones and zeros

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
np.linspace(1,9,4) # Will give four equally distributed numbers between 1 and 9

array([1.        , 3.66666667, 6.33333333, 9.        ])

In [14]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
np.eye(9) # Will give an identity matrix of 9X9 matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(3,9)

array([[0.63237984, 0.34248412, 0.15260885, 0.41622235, 0.96369866,
        0.64353435, 0.58772538, 0.03580513, 0.82240751],
       [0.02841748, 0.31618014, 0.42016513, 0.29198511, 0.91122856,
        0.54108301, 0.09689668, 0.05780933, 0.43509944],
       [0.30419223, 0.52786891, 0.32975258, 0.22982469, 0.42719867,
        0.46785217, 0.27228592, 0.96324321, 0.34613885]])

In [17]:
np.random.randn(3,6)

array([[-1.38752337,  0.43296814,  0.17029793,  0.08682941, -1.63914922,
         0.70738753],
       [-0.51596086,  0.55631873, -3.06542558, -0.69494722, -1.36914431,
        -0.60921644],
       [-0.45898557, -0.37811285, -0.06327055,  0.62371937,  0.1404995 ,
        -2.31573812]])

In [18]:
np.random.randint(3,18,4)

array([11, 12,  7,  7])

In [19]:
np.random.randint(3, 99, 18)

array([69, 12,  7, 44, 60, 85, 44, 84, 47, 84, 88, 11,  6, 95, 29, 76, 74,
       64])

In [20]:
sample = np.arange(3, 18)
sample

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [21]:
random_array = np.random.randint(3,18,9)
random_array

array([12, 13, 13,  3, 13,  7,  5, 16, 15])

In [22]:
sample.min()

3

In [23]:
sample.max()

17

In [24]:
sample.argmin()

0

In [25]:
random_array.min()

3

In [26]:
random_array.max()

16

In [27]:
list_o_list = ()

In [27]:
sample_array [:] = 1001
sample_array